# Etapa de build
FROM maven:3.9.2-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa de ejecución
FROM openjdk:17-jdk-slim
WORKDIR /app
# Copiamos el .jar con su nombre original
COPY --from=builder /app/target/gestion-restBackAutomange-1.0.jar gestion-restBackAutomange-1.0.jar
EXPOSE 13880
ENTRYPOINT ["java", "-jar", "gestion-restBackAutomange-1.0.jar"]

